--
-- PostgreSQL database dump
--

\restrict 8iuIpZNVIuDrxVUm7IAdsuDSWWzhMWzcRvsXXoejoLuhctqQ8xWhgL9CHv5rbTa

-- Dumped from database version 16.15 (Debian 16.15-1.pgdg13+2)
-- Dumped by pg_dump version 16.15 (Debian 16.15-1.pgdg13+2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

ALTER TABLE IF EXISTS ONLY public.enderecos DROP CONSTRAINT IF EXISTS fkifst74rmma55fhyky5g1l0589;
ALTER TABLE IF EXISTS ONLY public.clientes DROP CONSTRAINT IF EXISTS uk7wflw78ibh162cmq12ii6ffly;
ALTER TABLE IF EXISTS ONLY public.enderecos DROP CONSTRAINT IF EXISTS enderecos_pkey;
ALTER TABLE IF EXISTS ONLY public.clientes DROP CONSTRAINT IF EXISTS clientes_pkey;
DROP TABLE IF EXISTS public.enderecos;
DROP TABLE IF EXISTS public.clientes;
SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: clientes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.clientes (
    id integer NOT NULL,
    cpf character varying(11) NOT NULL,
    datanascimento date NOT NULL,
    email character varying(100) NOT NULL,
    nome character varying(100) NOT NULL
);


--
-- Name: clientes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.clientes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.clientes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: enderecos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.enderecos (
    id integer NOT NULL,
    bairro character varying(100) NOT NULL,
    cep character varying(8) NOT NULL,
    cidade character varying(100) NOT NULL,
    complemento character varying(100),
    logradouro character varying(150) NOT NULL,
    numero character varying(20) NOT NULL,
    uf character varying(2) NOT NULL,
    cliente_id integer NOT NULL
);


--
-- Name: enderecos_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.enderecos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.enderecos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: clientes; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.clientes (id, cpf, datanascimento, email, nome) FROM stdin;
1	12345678909	1990-03-14	ana.souza@example.com	Ana Beatriz Souza
2	23456789173	1985-07-22	bruno.lima@example.com	Bruno Henrique Lima
3	34567891228	1998-11-05	carla.ferreira@example.com	Carla Mendes Ferreira
4	45678912364	1979-01-30	daniel.costa@example.com	Daniel Oliveira Costa
5	56789123482	2001-05-18	eduarda.rocha@example.com	Eduarda Martins Rocha
6	67891234582	1992-09-09	felipe.santos@example.com	Felipe Araújo Santos
7	78912345664	1988-12-01	gabriela.pereira@example.com	Gabriela Nunes Pereira
8	89123456728	1975-04-26	henrique.barbosa@example.com	Henrique Alves Barbosa
9	91234567873	1995-08-12	isabela.dias@example.com	Isabela Carvalho Dias
10	13579246828	2000-02-29	joao.ribeiro@example.com	João Pedro Ribeiro
\.


--
-- Data for Name: enderecos; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.enderecos (id, bairro, cep, cidade, complemento, logradouro, numero, uf, cliente_id) FROM stdin;
1	Laranjeiras	22240003	Rio de Janeiro	Apto 302	Rua das Laranjeiras	120	RJ	1
2	Bela Vista	01310200	São Paulo	Sala 1204	Avenida Paulista	1578	SP	2
3	Centro	30160011	Belo Horizonte	\N	Rua da Bahia	905	MG	3
4	Centro	80020310	Curitiba	Casa 2	Rua XV de Novembro	450	PR	4
5	Boa Viagem	51020000	Recife	Apto 801	Avenida Boa Viagem	3200	PE	5
6	Icaraí	24230052	Niterói	\N	Rua Moreira César	88	RJ	6
7	Vitória	40080001	Salvador	Bloco B	Avenida Sete de Setembro	1020	BA	7
8	Centro Histórico	90020008	Porto Alegre	Loja 3	Rua dos Andradas	1234	RS	8
9	Meireles	60165121	Fortaleza	Apto 1501	Avenida Beira Mar	2500	CE	9
10	Asa Sul	70302000	Brasília	Bloco C	Setor Comercial Sul Quadra 2	22	DF	10
\.


--
-- Name: clientes_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.clientes_id_seq', 10, true);


--
-- Name: enderecos_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.enderecos_id_seq', 10, true);


--
-- Name: clientes clientes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.clientes
    ADD CONSTRAINT clientes_pkey PRIMARY KEY (id);


--
-- Name: enderecos enderecos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.enderecos
    ADD CONSTRAINT enderecos_pkey PRIMARY KEY (id);


--
-- Name: clientes uk7wflw78ibh162cmq12ii6ffly; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.clientes
    ADD CONSTRAINT uk7wflw78ibh162cmq12ii6ffly UNIQUE (cpf);


--
-- Name: enderecos fkifst74rmma55fhyky5g1l0589; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.enderecos
    ADD CONSTRAINT fkifst74rmma55fhyky5g1l0589 FOREIGN KEY (cliente_id) REFERENCES public.clientes(id);


--
-- PostgreSQL database dump complete
--

\unrestrict 8iuIpZNVIuDrxVUm7IAdsuDSWWzhMWzcRvsXXoejoLuhctqQ8xWhgL9CHv5rbTa

